"""Initial schema: menu, tables, orders

Revision ID: 91595dbbf53f
Revises: 
Create Date: 2025-12-06 11:58:06.925840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91595dbbf53f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply migration: Create initial database schema for OpenCafe.

    Creates 5 tables for managing cafe menu, tables, and orders.
    These tables mirror the SQLAlchemy models in infrastructure/persistence/.
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # Create menu_categories table (parent of menu_items)
    # Stores categories like "Coffee Drinks", "Pastries", etc.
    op.create_table('menu_categories',
    sa.Column('id', sa.String(), nullable=False),  # Primary key
    sa.Column('name', sa.String(), nullable=False),  # Category name
    sa.Column('description', sa.String(), nullable=False),  # Category description
    sa.PrimaryKeyConstraint('id')  # id is the primary key
    )

    # Create tables table (independent, referenced by orders)
    # Stores physical seating tables in the cafe
    op.create_table('tables',
    sa.Column('id', sa.String(), nullable=False),  # Primary key
    sa.Column('number', sa.Integer(), nullable=False),  # Table number (display)
    sa.Column('capacity', sa.Integer(), nullable=False),  # Max people
    sa.Column('location', sa.String(), nullable=False),  # Physical location
    sa.PrimaryKeyConstraint('id')  # id is the primary key
    )

    # Create menu_items table (child of menu_categories)
    # Stores items on the menu like "Espresso", "Croissant", etc.
    op.create_table('menu_items',
    sa.Column('id', sa.String(), nullable=False),  # Primary key
    sa.Column('name', sa.String(), nullable=False),  # Item name
    sa.Column('description', sa.String(), nullable=False),  # Item description
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),  # Price with cents
    sa.Column('category_id', sa.String(), nullable=False),  # Foreign key to categories
    sa.Column('available', sa.Integer(), nullable=False),  # 1=available, 0=unavailable
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),  # Link to category
    sa.PrimaryKeyConstraint('id')  # id is the primary key
    )
    # Add index for category_id lookups (finding all items in a category)
    op.create_index('idx_menu_items_category', 'menu_items', ['category_id'])

    # Create orders table (child of tables, parent of order_items)
    # Stores customer orders placed at tables
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),  # Primary key
    sa.Column('table_id', sa.String(), nullable=False),  # Foreign key to tables
    sa.Column('status', sa.String(), nullable=False),  # Order status (pending, confirmed, etc.)
    sa.Column('created_at', sa.DateTime(), nullable=False),  # When order was placed
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),  # Link to table
    sa.PrimaryKeyConstraint('id')  # id is the primary key
    )

    # Create order_items table (child of orders)
    # Stores individual items within an order
    # Uses SNAPSHOT pattern (stores name/price, not just menu_item_id reference)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),  # Auto-increment primary key
    sa.Column('order_id', sa.String(), nullable=False),  # Foreign key to orders
    sa.Column('menu_item_id', sa.String(), nullable=False),  # Reference (NOT foreign key!)
    sa.Column('menu_item_name', sa.String(), nullable=False),  # SNAPSHOT: name at order time
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),  # SNAPSHOT: price at order time
    sa.Column('quantity', sa.Integer(), nullable=False),  # How many ordered
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),  # Link to order
    sa.PrimaryKeyConstraint('id')  # id is the primary key
    )
    # Add index for order_id lookups (finding all items in an order)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('menu_items')
    op.drop_table('tables')
    op.drop_table('menu_categories')
    # ### end Alembic commands ###
